site_name: Zephyr/nRF Connect SDK Documentation
nav:
  - Home: index.md
  - Programming: programming.md
theme: 
  name: material            # Use the Material theme for MkDocs
  palette: 
    scheme: slate
    primary: deep purple
    accent: teal
  logo: assets/zephyr.jpg
  features:
    - navigation.tabs
    - navigation.expand
    - toc.integrate
    - content.code.copy
    - content.code.select
plugins:
  - search
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
